stages:
  - lint
  - notification

tslint:
  stage: lint
  script:
    - sh ./bin/tslint.sh

send_change_log:
  stage: notification
  script:
    - npm install --registry https://registry.npm.taobao.org
    - gulp
    - node ./lib/js/tools/sendchangelog.js
